name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  backend-tests:
    name: Backend Tests (Python/Django)
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up test environment
      run: |
        export DJANGO_SETTINGS_MODULE=homelab_dashboard.settings
        export SECRET_KEY=test-secret-key-for-ci
        export FIELD_ENCRYPTION_KEY=$(python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
    
    - name: Run database migrations
      env:
        DJANGO_SETTINGS_MODULE: homelab_dashboard.settings
        SECRET_KEY: test-secret-key-for-ci
        FIELD_ENCRYPTION_KEY: ${{ secrets.FIELD_ENCRYPTION_KEY || 'gAAAAABhqQJ3VvJ-3K5qQz7_QxLJ6N5TQxZJ5rF1x2YqF6J9xJ3F1xJ='  }}
      run: |
        python manage.py migrate --noinput
    
    - name: Run backend tests
      env:
        DJANGO_SETTINGS_MODULE: homelab_dashboard.settings
        SECRET_KEY: test-secret-key-for-ci
        FIELD_ENCRYPTION_KEY: ${{ secrets.FIELD_ENCRYPTION_KEY || 'gAAAAABhqQJ3VvJ-3K5qQz7_QxLJ6N5TQxZJ5rF1x2YqF6J9xJ3F1xJ='  }}
      run: |
        pytest tests/ \
          --cov=dashboard \
          --cov-report=xml \
          --cov-report=term \
          -v \
          --tb=short
    
    - name: Upload backend coverage
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage-${{ matrix.python-version }}
        path: ./coverage.xml
        retention-days: 7
  
  frontend-tests:
    name: Frontend Tests (JavaScript/Jest)
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['18.x', '20.x']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run frontend tests
      run: npm test -- --coverage
    
    - name: Upload frontend coverage
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage-${{ matrix.node-version }}
        path: ./coverage/
        retention-days: 7
  
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up test environment
      run: |
        export DJANGO_SETTINGS_MODULE=homelab_dashboard.settings
        export SECRET_KEY=test-secret-key-for-ci
        export FIELD_ENCRYPTION_KEY=$(python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
    
    - name: Run database migrations
      env:
        DJANGO_SETTINGS_MODULE: homelab_dashboard.settings
        SECRET_KEY: test-secret-key-for-ci
        FIELD_ENCRYPTION_KEY: ${{ secrets.FIELD_ENCRYPTION_KEY || 'gAAAAABhqQJ3VvJ-3K5qQz7_QxLJ6N5TQxZJ5rF1x2YqF6J9xJ3F1xJ='  }}
      run: |
        python manage.py migrate --noinput
    
    - name: Run integration tests
      env:
        DJANGO_SETTINGS_MODULE: homelab_dashboard.settings
        SECRET_KEY: test-secret-key-for-ci
        FIELD_ENCRYPTION_KEY: ${{ secrets.FIELD_ENCRYPTION_KEY || 'gAAAAABhqQJ3VvJ-3K5qQz7_QxLJ6N5TQxZJ5rF1x2YqF6J9xJ3F1xJ='  }}
      run: |
        pytest tests/ -m "integration" -v
  
  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Run flake8
      run: flake8 dashboard/ homelab_dashboard/ --count --max-line-length=120 --statistics
      continue-on-error: true
    
    - name: Check code formatting with black
      run: black --check dashboard/ homelab_dashboard/
      continue-on-error: true
    
    - name: Check import sorting with isort
      run: isort --check-only dashboard/ homelab_dashboard/
      continue-on-error: true
  
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, integration-tests]
    if: always()
    
    steps:
    - name: Check test results
      run: |
        echo "Backend Tests: ${{ needs.backend-tests.result }}"
        echo "Frontend Tests: ${{ needs.frontend-tests.result }}"
        echo "Integration Tests: ${{ needs.integration-tests.result }}"
        
        if [ "${{ needs.backend-tests.result }}" != "success" ] || \
           [ "${{ needs.frontend-tests.result }}" != "success" ] || \
           [ "${{ needs.integration-tests.result }}" != "success" ]; then
          echo "Some tests failed!"
          exit 1
        fi
        
        echo "All tests passed!"
